sudo: required
services:
    - docker

before_install:
    - docker build -t chandank5265/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chandank5265/docker-react npm run test -- --coverage