sudo: required
services:
    - docker

before_install:
    - docker build -t chandank5265/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chandank5265/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react1"
    env: "DockerReact1-env"
    bucket_name: "elasticbeanstalk-us-east-2-547562571778"
    bucket_path: "docker-react1"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY